config/routes.rb
Rails.application.routes.draw do
  resources :articles

  root  "posts#index"
  resources :posts

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :publish_date)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(id: :desc)
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
        format.js
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :publish_date %><br>
    <%= f.datetime_select :publish_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="container-fluid" ng-app='myApp'>
<div ng-controller='articles_controller'>
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>
 <input type='text' ng-model='search_text'>
      

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Publish date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr ng-repeat ='article in articles | filter:search_text'> 
        <td> {{ article.title }}</td>
        <td> {{ article.publish_date }}</td>
      </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>
<input type="text" ng-model="newArticle"/>
  
 <button class="btn btn-default" ng-click='addArticle()' type="submit">New Article</button>
</div>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @article.publish_date %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyAjax</title>
  <%= stylesheet_link_tag    'application',media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>

<% 
#<link rel="stylesheet" href="../assets/stylesheets/bootstrap.min.css">
#<link rel="stylesheet" href="../assets/stylesheets/bootstrap-theme.min.css">
#<script src="../assets/javascripts/bootstrap.min.js"></script>		
%>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class = "col-md-4 blog-main box text-center" id = "post_<%= post.id %>">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title"> <%= post.title%></h3>
			<p> <%= post.description%></p>
			
		</div>
		<div class="panel-body">
		<div class="btn-group" role = "group">
			<button type="button" class="btn btn-warning" data-toggle = "modal" data-target ="#myupdatepost_<%= post.id %>">EDIT</button>
			
			<%= link_to 'Destroy', post, method: :delete,class: "btn btn-danger", remote: true %>

		</div>
		</div>

	</div>

	<%= form_for(post, method: :put,remote: true) do |f|%>
		<div class="modal" id ="myupdatepost_<%= post.id %>" tabindex ="-1">
			<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h4 class="modal-title" id="myModalLabel">Edit
							</h4>
						</div>
						<div class="model-body">
							<div class="field">
								 <%= f.label :title %>
         					 <%= f.text_field :title, class: "form-control post_title" %>
							</div>
							<div class="field">
						          <%= f.label :description %>
						         <%= f.text_area :description,class: "form-control post_description" %>
						        </div>
						</div>
						<div class="modal-footer">
							<button type="button" id ="myupdatepost_<%= post.id%>" class = "btn btn-default" data-dismiss ="modal">Close
								
							</button>
							<%= submit_tag "Update",class: "btn btn-default" %>
						</div>
					</div>
			</div>			
		</div>
	<% end %>

</div>

app/views/posts/create.js.erb
$("#mynewpost").modal('hide');
$(".post_title").val('');
$(".post_description").val('');
$("#container_posts").prepend("<%= j render @post %>");
$("#post_<%= @post.id%>").hide().fadeIn(1000);

app/views/posts/destroy.js.erb
$("#post_<%= @post.id%>").fadeOut(500,function(){
	$(this).remove();
});

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
  <!-- Button trigger modal -->
<div class="container">
<div class="row">
<div class="text-center">
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#mynewpost">
      New Post
    </button>
    </div>
</div>
<div class="row" id ="container_posts">
  <%= render @posts %>
</div>
<%= form_for(@post, remote: true) do |f| %>
<div class="modal fade" id="mynewpost" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Post</h4>
      </div>
      <div class="modal-body">
        <div class="field">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control post_title" %>

        </div>
        <div class="field">
          <%= f.label :description %>
         <%= f.text_area :description,class: "form-control post_description" %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          
        <%= submit_tag "Create",class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>
<% end %>
<!-- Modal -->

</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/update.js.erb
$("#myupdatepost_<%=@post.id %>").modal('hide');

$("#post_<%= @post.id%>").fadeOut(500,function(){
	$(this).remove();
	$("#container_posts").prepend("<%= j render @post %>");
});